---
- include_tasks: ./containers/traefik.yml
- include_tasks: ./containers/homepage.yml
- include_tasks: ./containers/portainer.yml
- include_tasks: ./containers/prometheus-grafana.yml
- include_tasks: ./containers/jenkins.yml
