remove_docker_volumes: false
jenkins_ip_address: "172.20.0.50"
jenkins_port: "8080"
jenkins_public_url: "http://jenkins.localhost"
jenkins_admin_id: "admin"
jenkins_admin_password: "admin123"
jenkins_agent_user: "{{ username | default('', true) }}"
jenkins_remote_root_dir: "/home/{{ jenkins_agent_user }}/jenkins"