remove_docker_volumes: false
jenkins_ip_address: "172.20.0.50"
jenkins_port: "8080"
jenkins_public_url: "http://jenkins.localhost"
jenkins_agent_port: "18080"
jenkins_agent_url: "http://localhost:{{ jenkins_agent_port }}"
jenkins_admin_id: "admin"
jenkins_admin_password: "change-me-before-first-run"
jenkins_agent_user: "{{ username | default('', true) }}"
jenkins_remote_root_dir: "/home/{{ jenkins_agent_user }}/jenkins"